### ISSUE TITLE
chore: Add Snowflake config for easy deploy to Streamlit-in-Snowflake/SiS

### ISSUE THREAD

**Issue by lawrenceadams** [londonaicentre/PhenoLab#89]
snowflake.yaml

```yaml
definition_version: 2
entities:
  ladams_phenolab:
    type: streamlit
    identifier: ladams_phenolab
    stage: ladams_stage
    query_warehouse: INTELLIGENCE_XS
    main_file: PhenoLab.py
    pages_dir: pages
    artifacts:
      - pages/
      - data/
      - sql/
      - utils/
      - phmlondon/
      - PhenoLab.py
      - environment.yml
```

environment.yaml

```yaml
name: ladams_phenolab_env
channels:
  - snowflake
dependencies:
  - numpy
  - pandas
  - pyyaml
  - fastparquet
  - lxml
  - python-dotenv
  - streamlit
  - openpyxl
  - polars
```
